apiVersion: v1
kind: Service
metadata:
  labels:
    service: app-coworking
  name: app-coworking
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 5153
      targetPort: 5153
  selector:
    service: app-coworking
